#!/bin/bash
#

set AUDIODEV=hw:1

DECODER=wsprcan/k9an-wsprd 
PAPLAY=paplay
and=&
IQFILE="iq.wav"
AUDIOFILE="audio.wav"
DEMO="data/iq-16b.wav"

# set oscillator
fclockgen/fclockgen
echo -n "Excuting software demo for play iq-16b.wav"
${DECODER}&
${PAPLAY} ${DEMO}
#${DECODER}
echo -n "Demo decoding finish "

while true
do
        sec=$(date +'%S')
        min=$(date +'%M')
        # wait for an even minute
        if (("10#$min" % 2 == 0 && "10#$sec" == 0 )); then
                echo -n "Executing wspr_decode "
                date
                # record audio
                rec -V1 -c 1 -t wav ${IQFILE} trim 0 118 &>/dev/null
                # convert to 16 bit mono
                sox ${IQFILE} -c 1 -t wav -r 12000 -b 16 ${AUDIOFILE}
                # decode WSPR
                ${DECODER} ${AUDIOFILE}
        elif ((10#$sec < 49)); then
                sleep 10
        fi
done
